### ISSUE TITLE
Intransparent Pricing of the Core API | 200$/month

### ISSUE THREAD

**Issue by philippzentner** [veritrans/veritrans.github.io#135]
This is a complaint. 

We spent a week on implementing your API and work through your documentation, just to get a formal contract that suddently asks us to pay **200$/month just for using the Core API**. We're bootstrapping the business and now need to consider launching later and switching to Doku.

**Please document your pricing.** Very intransparent and frustrating. I also do not think that this is the right growth-strategy for an API driven business. (See e.g. Stripe)

**Comment by rizdaprasetya** [comment]
Hi @philippzentner though the docs is not intended to display pricing information, since it explain about technical integrations and maintained by our tech team, pricing info is on the main website and managed by our Business Team. We acknowledge the confusion and forwarded this concern to our Business Team.

Our Business Team would like to have contact with you directly and would like to offer solution to settle the matter, can you inform us your registered `Merchant ID`, or let us know any contact details that we can reach you with?

Thank you.

**Comment by philippzentner** [comment]
Hey @rizdaprasetya 
You're absolutely right with this. Should not be part of the technical documentation. Was more a general thing. It should be written down here: https://midtrans.com/payments/pricing

But isn't. Just confused, as your business model is supposed to be purely transaction driven. 
Your team can reach us at +62 878-0231-2522 | Merchant ID G197461307

Thanks a lot for the great support here. :)

**Comment by rizdaprasetya** [comment]
Yes correct @philippzentner , we agree that we could and should be better on that.

We'll forward the contact and our Business Team will be in touch as soon they are available to discuss the possible solution.

Our pleasure 👌, Thanks!

**Comment by rizdaprasetya** [comment]
I believe our Business team have already made announcement on the Core API pricing. So there should no hidden fees or in-transparent pricing anymore. All pricing should follows the:
https://midtrans.com/payments/pricing

Thank you
