### ISSUE TITLE
Configuring Payment Channels

### ISSUE THREAD

**Issue by mshenoy83** [veritrans/veritrans.github.io#89]
There is absolutely no documentation on configuring payment channels using Snap Api.

**Comment by rizdaprasetya** [comment]
Hi @mshenoy83 

Thanks for asking, you can try to take a look at: 
http://docs.midtrans.com/en/snap/other_features.html

Or `enabled_payments` part here:
https://snap-docs.midtrans.com/#json-parameter-request-body

Or is it something else you are trying to look for?

Thanks.

**Comment by mshenoy83** [comment]
Hi @rizdaprasetya support team came back to me on this, to enable payment channels. But it would be helpful if the process is documented, I spent a while debugging because I thought I hadn't sent the right data to the snap function.

**Comment by rizdaprasetya** [comment]
We do have documentation for which payment channels you would like to enable:
http://docs.midtrans.com/en/snap/other_features.html
https://snap-docs.midtrans.com/#json-parameter-request-body

But if you mean is configuring payment channels arrangement, yes we haven't document it yet, but it's already available on the dashboard setting menu.

Thanks for suggesting.

**Comment by mshenoy83** [comment]
@rizdaprasetya  Yes, I did send that data to the api and the response I got was payment channel was not enabled. It was only after I raised a ticket that support enabled it and I started recieving the right response.

**Comment by Paxa** [comment]
Make sense. Currently need to contact shoot for every change in payment channel settings.

@rizdaprasetya, any plans to add this feature in dashboard?

**Comment by rizdaprasetya** [comment]
@mshenoy83 I see now, the case is your sandbox account payment channels didn't properly get activated when you're signing up. What we did is re-activate those channels.
We didn't get your question because you we're mentioning:
> There is absolutely no documentation on configuring payment channels using Snap Api.
Actually the doc & feature are correct, but unfortunately your account is not activated at that moment.
If you were asking: "Why can't I see any enabled payment channels on my payment page" and/or attach a screenshot that would help us understand better.
Sorry for the misunderstanding. We always suggest to ask for support via email so we can avoid these kind of misunderstanding. 

Thanks.

@Paxa The payment channel selection feature is available both on Dashboard (for Snap) & via API payload (for Core Api & Snap). 
This one case is exception, where someone signed up for dashboard account, but sandbox account payment channel didn't properly generated/populated (job didn't triggered, or job stopped), so he got 0 payment channel activated. So regardless of feature above, the user will seems to get no payment enabled. Dashboard Team will need to re-trigger the job for the account. We've let the team know about these kind of cases.
